sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t stvncharles/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stvncharles/docker-react npm run test